 
# RMF door parameters

### template ###
door:
  name: "Door_East"
  url: "10.0.1.81"
  port: "1080"
  io_pin: 0
  door_id: "Door_East"
  door_signal_period: 3.0 # Seconds
  door_close_feature: True 

door_subscriber:
  topic_name: "adapter_door_requests"

door_publisher:
  topic_name: "door_states"
  door_state_publish_period: 1.0 # Seconds
